cache:
- bundler
sudo: false
branches:
only:
- develop
cache: cocoapods
language: objective-c
before_install:
 - pod install --project-directory=CheckinAppChallenge 
xcode_workspace: CheckinAppChallenge.xcworkspace # path to your xcodeproj folder
xcode_scheme: CheckinAppChallenge
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1935942c-85a7-4abe-83c0-8c1cb3a3eb60
